filebeat.inputs:
- type: log
  paths:
    - /var/log/*log
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match: after
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: "message"
  json.expand_keys: true


processors:
 - decode_json_fields:
    fields: ["message"]
    target: json
    max_depth: 10

output.elasticsearch:
  hosts: ["http://42.96.43.194:5100"]

setup.kibana:
  host: "http://42.96.43.194:5050"