filebeat.inputs:
- type: log
  paths:
    - /var/log/*log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: "message"
  json.expand_keys: true
  json.ignore_decoding_error: true


processors:
 - decode_json_fields:
    fields: ["message"]
    target: ""
    max_depth: 10
    overwrite_keys: true

output.elasticsearch:
  hosts: ["http://42.96.43.194:5100"]

setup.kibana:
  host: "http://42.96.43.194:5050"